version: '2'
services:
  jenkins_master:
    build: .
    container_name: jenkins-master
    environment:
    - JAVA_OPTS=-Xmx2048m
    - DOCKER_HOST=tcp://host.docker.internal:2375
    user: root
    restart: always
    volumes:
    - jenkins-master:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8090:8080"
      - "50000:50000"
      - "8443:8443"
      
  jenkins_node:
    build: ./slave
    container_name: node
    user: root
    restart: always

    
