version: '2'
services:
  jenkins_master:
    build: .
    container_name: jenkins-master
    environment:
    - JAVA_OPTS=-Xmx2048m
    - DOCKER_HOST=tcp://host.docker.internal:2375
    user: root
    restart: always
    volumes:
    - jenkins-master:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8090:8080"
      - "50000:50000"
      - "8443:8443"
      
  jenkins_node:
    build: ./slave
    container_name: node
    user: root
    restart: always
expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDRX1Xdd0bjWcGN2dd62bin8W+RYDssdPccyYe8hL4+xBcGyHDoTNtH8lYdvFRbO1BT+sZy2uX42Gn8+i1p1XlQzMSqNgBE8UxAhk/zcoHQgZZ5/y/lDaF1pWzwmzN5UP39E4emdN0BUN0BkzQ8oF1hYc3Oi/EQP/9u8Oo/TLMQLhHAvBAiKxwHNaYhCDJw/84gdZeHztujejt8EiYavjH6W+mP68R2M5h/Vaf+cS0TwgINhiIf/rUKBIbM1/RogMXbL6gZK4/s15fDSvGPGFeXtemmqDpEgiJAlP9Yd2ykuutXw46TkE+7hm/0iC4V6U2KyjqWs/M62gsVEi6VrqU5 ubuntu@ip-172-31-91-158

